### ISSUE TITLE
Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION

### ISSUE THREAD

**Issue by rahulraka** [ClickHouse/clickhouse-java#1881]
I have introduced a new HTTP5 Client in my project, after adding it If I am doing any Save or read call  I am getting below error.

Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION java.lang.NoClassDefFoundError: org/apache/hc/client5/http/config/ConnectionConfig at com.clickhouse.client.http.ApacheHttpConnectionImpl$HttpConnectionManager.(ApacheHttpConnectionImpl.java:377) at com.clickhouse.client.http.ApacheHttpConnectionImpl.newConnection(ApacheHttpConnectionImpl.java:95) at com.clickhouse.client.http.ApacheHttpConnectionImpl.(ApacheHttpConnectionImpl.java:82) at com.clickhouse.client.http.ClickHouseHttpConnectionFactory.createConnection(ClickHouseHttpConnectionFactory.java:32) at com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:119) at com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:35) at com.clickhouse.client.AbstractClient.getConnection(AbstractClient.java:198) at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:163) at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280) at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282) at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294) at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349) at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:878) at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154) at com.clickhouse.jdbc.internal.Click, HouseStatementImpl.executeInsert(ClickHouseStatementImpl.java:336) at

Not sure why it is happening, Below are the conflicting dependencies

 <dependency>
            <groupId>org.apache.httpcomponents.core5</groupId>
            <artifactId>httpcore5</artifactId>
            <version>5.1</version> 
        </dependency>

        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.6.1</version>
        </dependency>,
        
        not sure if it is a bug, can anyone help me with it...

**Comment by chernser** [comment]
Hi, @rahulraka!

here is how we add Apache http client in example projects https://github.com/ClickHouse/clickhouse-java/blob/main/examples/client/pom.xml#L99

 Dependency on `clickhouse-jdbc` do not add http client by default. 
 Would you please give us example of what dependencies in your application look like? 
 
 Thanks!

**Comment by rahulraka** [comment]
Hi, @chernser !,
I started facing issue as soon as I put below dependency for some other features.

<dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>5.1</version> 
        </dependency>
        
        
        Please let me know what colud be done here, to solve this, I have tried upgrading/ downgrading for both dependencies.
        Thanks!!

**Comment by chernser** [comment]
@rahulraka 
the issue may be that we are using 5.3.1 version: https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5/5.3.1

Would you please try upgrading? 
If possible would you please share output of the command `mvn dependency:tree`? I would like to see how dependencies are applied. 

Thanks!

**Comment by rahulraka** [comment]
@chernser,
Thanks for the prompt response, the issue got resolved after upgrading the version specifically to 5.3.1.
Thanks!!

**Comment by hipp0gryph** [comment]
@chernser hello! I get error like that.
```
Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION
java.lang.NoClassDefFoundError: org/apache/hc/core5/io/ModalCloseable
```
I use [httpclient5/5.3.1](https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5/5.3.1) and drive 0.7.1 patch 1. Thank you in advance!
